# Generated by Django 5.2.4 on 2025-09-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='course_class',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='date_of_preparation',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='name_of_institution',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='number_of_learners',
        ),
    ]
