# Generated by Django 5.2.4 on 2025-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
