# Generated by Django 5.2.4 on 2025-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=20),
        ),
    ]
