# Generated by Django 5.2.4 on 2025-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0004_alter_unit_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='competency',
            field=models.CharField(blank=True, choices=[('BC', 'Basic Competency'), ('CR', 'Core Competency'), ('CC', 'Common Competency')], default='BC', max_length=2, null=True),
        ),
    ]
