# Generated by Django 5.2.4 on 2025-08-31 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0005_unit_competency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_number', models.CharField(max_length=15)),
                ('name_of_institution', models.CharField(max_length=200)),
                ('date_of_preparation', models.DateField()),
                ('number_of_learners', models.IntegerField()),
                ('course_class', models.CharField(max_length=100)),
                ('number_of_weeks', models.IntegerField()),
                ('number_of_sessions_per_week', models.IntegerField()),
                ('hours_per_session', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TrainerApp.transactions')),
            ],
        ),
    ]
