# Generated by Django 5.2.4 on 2025-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0006_transactions_trainingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='hours_per_session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='number_of_sessions_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='number_of_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
