# Generated by Django 5.2.4 on 2025-09-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerApp', '0007_alter_trainingsession_hours_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
